### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by YimeiZhang0229** [zwzhangzzz/SNIPER_pytorch#1]
作者您好，非常感谢您出色的工作！我最近在复现您的代码时发现缺少验证、测试和评价指标的相关代码。为了解决这个问题，我参考了TensorFlow版本的代码进行了复现，但在model.py的第31行遇到了以下错误：“line 31, in forward
    all_data_dynamic_diff = torch.cat(all_data_dynamic_diff, axis=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors” 请问您知道这是什么原因吗？如果方便的话，能否提供更详细的PyTorch版本代码？非常感谢！

**Comment by Zhanwei-Z** [comment]
The code for the torch version is incomplete and has not been evaluated; it is only provided as a reference. The complete official code is based on our [TensorFlow](https://github.com/Zhanwei-Z/SNIPER_pytorch). Fortunately, the torch version closely corresponds to the TensorFlow version, line by line. With the TensorFlow version as a reference, reproducing the code in torch is straightforward.
